### ISSUE TITLE
issue with computing guide 

### ISSUE THREAD

**Issue by swilliams922** [bircibrain/computingguide#8]
Hi there! I have used the computing guide to convert my MRI data into BIDS format with great success back around late September/early October using singularity. The following code worked like a charm for me: 

singularity run --bind `pwd`/cogneuro:/data docker://rhancock/birc-bids bidscoiner.py -f /data/raw /data/bids/

I have now gone back to convert a new set of participants (after renaming the previously converted participants so they weren't converted again) and this code now gives me the following error: 
/singularity: line 9: exec: bidscoiner.py: not found

I did notice that the bircibrain/birc-bids repository was updated in mid-October, so I wasn't sure if that could contribute to this issue or mean the computing guide would need to be edited or updated. 

Any help/guidance you can offer would be greatly appreciated! Please let me know if any additional information is needed from my end. 

Thanks, 
Samantha Williams

**Comment by rhancockn** [comment]
Hi Samantha,
Sorry for your trouble! The October update introduced a newer version of
bidscoiner and is likely the source of trouble (and yes, I do need to
update the website-thanks for the reminder!)
You might try either
- changing your script to call bidscoiner instead of bidscoiner.py
- use the rhancock/birc-bids:2.3 image, which should reproduce the
earlier behavior.

Please let me know if either of these solve your problem.
Roeland Hancock

**Comment by swilliams922** [comment]
Hi Roeland,

Thank you for the quick reply. I used your second suggestion and it worked! I was able to convert all my new participants. I really appreciate the help! 

Best,
Samantha
